test:
  stage: test
  script:
  - bundle install
  - bundle exec rake test
  tags:
  - ruby2.2.3

production:
  type: deploy
  script:
    - docker build -t registry.adcombi.com:5000/ruby-dummy-app .
    - docker push registry.adcombi.com:5000/ruby-dummy-app
  only:
  - master
  tags:
  - privileged