test:
  stage: test
  script:
  - bundle install
  - bundle exec rake test
  tags:
  - ruby2.2.3

production:
  type: deploy
  script:
    - "export SHORT_SHA=$(echo $CI_BUILD_REF |cut -c1-8)"
    - "echo Branch/Tag: $CI_BUILD_REF_NAME"
    - "echo Commit: $CI_BUILD_REF"
    - "echo CI Build: $CI_BUILD_ID"
    - "echo Short SHA: $SHORT_SHA"
    - docker build -t registry.adcombi.com:5000/ruby-dummy-app:branch.$CI_BUILD_REF_NAME-commit.$SHORT_SHA-build.$CI_BUILD_ID .
    - docker push registry.adcombi.com:5000/ruby-dummy-app:branch.$CI_BUILD_REF_NAME-commit.$SHORT_SHA-build.$CI_BUILD_ID
  only:
  - master
  tags:
  - privileged